version: "3.8"
services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=GxtjDzMhN_q2K2AKDPAuaNLds
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P GxtjDzMhN_q2K2AKDPAuaNLds -Q 'select 1' -l 5"]
      timeout: 10s
      retries: 10
      interval: 10s
  app:
    image: "tianon/true"
    depends_on:
      mssql:
        condition: service_healthy
